### ISSUE TITLE
Change "ArchiWebHandler.CachedAccessToken" to "Bot.AccessToken"

### ISSUE THREAD

**Issue by sffxzzp** [DevSplash/ASFAutoClaimStickers#1]
https://github.com/JustArchiNET/ArchiSteamFarm/releases/tag/5.5.2.3
> `ArchiWebHandler.CachedAccessToken` is now deprecated, use `Bot.AccessToken` instead. It'll be removed in the next version, until then it's available to allow smooth migration and internally maps to `Bot.AccessToken`.

affected:
https://github.com/DevSplash/ASFAutoClaimStickers/blob/5a180ac48f291e58029af8c64a9e37d71dbf7218/AutoClaimStickers/AutoClaimStickers.cs#L100

**Comment by DevSplash** [comment]
Closed by cd750f50df3d1d6c8b34975df943bd8af6fd5c20
