### ISSUE TITLE
Can you add autoupdate setting or update command?

### ISSUE THREAD

**Issue by visualwind** [DevSplash/ASFAutoClaimStickers#3]
Like this plugin: https://github.com/chr233/ASFEnhance

**Comment by DevSplash** [comment]
I'm not sure if this feature is necessary. Usually this plugin won't be updated unless ASF changes the plugin API (e.g. v5.5.2.3 and v6.0.0.3). In this case the plugin won't be loaded, and ASF might even crash on startup. Therefore, the code related to the auto-update feature also cannot be executed, which means that the auto-update feature is unnecessary most of the time.

**Comment by DevSplash** [comment]
Closed by 88dd86f246db53271b238cec4c68a160abc35bcf
ASF added automatic plugin updates interfaces in [6.0.1.2](https://github.com/JustArchiNET/ArchiSteamFarm/releases/tag/6.0.1.2).
You can try this [pre-release version](https://github.com/DevSplash/ASFAutoClaimStickers/releases/tag/1.0.2.1).
